# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Perform one-shot adjacent swapping for each element.
#'
#' @param data A list of vector and integer.
#'   
#' @export
#'
swap_pass <- function(data) {
    .Call('_ASURAT_swap_pass', PACKAGE = 'ASURAT', data)
}

#' Perform bubble sorting, counting the number of steps.
#'
#' @param data A list of vector and integer.
#' @param data A list of vector and integer.
#'   For example, in R code, data = list(vec = c(1, 0, 1, 1, 0, ...), cnt = 0).
#'   The integer (cnt = 0) is the initial number of steps for bubble sorting.
#'
#' @export
#'
bubble_sort <- function(data) {
    .Call('_ASURAT_bubble_sort', PACKAGE = 'ASURAT', data)
}

